name: Build and Test Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1) Linux: manylinux-колёса для всех CPython
  build_manylinux:
    name: Build Linux wheels (manylinux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build manylinux wheels
        run: cibuildwheel --output-dir dist/

      - name: List Linux wheels
        run: ls -l dist/

      - name: Upload Linux wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: dist/*.whl

  # 2) Windows: bdist_wheel для каждой версии Python
  build_windows:
    name: Build Windows wheels
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build deps
        run: pip install --upgrade pip setuptools wheel cython

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: List Windows wheels
        run: dir dist

      - name: Upload Windows wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels-py${{ matrix.python-version }}
          path: dist/*.whl

  # 3) macOS: то же самое
  build_macos:
    name: Build macOS wheels
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build deps
        run: pip install --upgrade pip setuptools wheel cython

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: List macOS wheels
        run: ls -l dist/

      - name: Upload macOS wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels-py${{ matrix.python-version }}
          path: dist/*.whl
