name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels for Python ${{ matrix.python-version }} on ARM64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for aarch64
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build wheel in ARM64 container
        shell: bash
        run: |
          docker run --rm --platform linux/arm64 \
            -v "$(pwd)":/project -w /project \
            python:${{ matrix.python-version }}-slim-bookworm bash -eux -c "
              # 1) Обновляем списки пакетов
              apt-get update

              # 2) Устанавливаем сборочные зависимости
              apt-get install -y build-essential libffi-dev

              # 3) Обновляем pip, setuptools и wheel, устанавливаем Cython
              python -m pip install --upgrade pip setuptools wheel cython

              # 4) Собираем wheel
              python setup.py bdist_wheel
            "

      - name: List wheels
        run: ls -l dist/

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-arm64-python${{ matrix.python-version }}
          path: dist/*.whl
