name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels for Python ${{ matrix.python-version }} on ${{ matrix.architecture }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        architecture: ["aarch64"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.architecture == 'aarch64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython setuptools wheel

    - name: Build wheel for aarch64
      if: matrix.architecture == 'aarch64'
      run: |
        pip install crossenv
        python -m crossenv $(which python) venv --sys-cflags="-march=armv8-a" --sys-ldflags="-march=armv8-a"
        source venv/bin/activate
        pip install cython setuptools wheel
        python setup.py bdist_wheel
        deactivate

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.architecture }}-python${{ matrix.python-version }}
        path: dist/*.whl
